# Generated by Django 5.2.11 on 2026-08-14 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0003_alter_question_option_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('global_student_id', models.UUIDField(db_index=True, unique=True)),
                ('student_code', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('grade_id', models.BigIntegerField()),
                ('section_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=150, null=True)),
                ('parent_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTestResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attempt_id', models.UUIDField(db_index=True)),
                ('assessment_id', models.BigIntegerField(db_index=True)),
                ('subsection_id', models.BigIntegerField(db_index=True)),
                ('selected_response_json', models.JSONField(blank=True, null=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('subsection_started_at', models.DateTimeField(blank=True, null=True)),
                ('subsection_completed_at', models.DateTimeField(blank=True, null=True)),
                ('subsection_time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('test_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='question.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_responses', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt_id', 'question'), name='unique_question_per_attempt')],
            },
        ),
    ]
