# Generated by Django 5.2.11 on 2026-08-14 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_assessmentstructure_section_code_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttestresponse',
            name='subsection_id',
        ),
        migrations.AddField(
            model_name='studenttestresponse',
            name='subsection',
            field=models.ForeignKey(db_column='subsection_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='student_test_responses', to='assessment.assessmentstructure', to_field='subsection_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenttestresponse',
            name='subsection_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted')], db_index=True, default='IN_PROGRESS', max_length=20),
        ),
    ]
