# Generated by Django 5.2.11 on 2026-08-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentStructure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grade_id', models.BigIntegerField()),
                ('grade_name', models.CharField(max_length=50)),
                ('assessment_id', models.BigIntegerField()),
                ('assessment_code', models.CharField(max_length=30)),
                ('assessment_name', models.CharField(max_length=200)),
                ('assessment_description', models.TextField(blank=True, null=True)),
                ('section_id', models.BigIntegerField()),
                ('section_code', models.CharField(max_length=30)),
                ('section_name', models.CharField(max_length=100)),
                ('section_display_order', models.IntegerField()),
                ('subsection_id', models.BigIntegerField(unique=True)),
                ('subsection_code', models.CharField(max_length=30)),
                ('subsection_name', models.CharField(max_length=100)),
                ('subsection_description', models.TextField(blank=True, null=True)),
                ('subsection_display_order', models.IntegerField()),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assessment_structure',
                'ordering': ['section_display_order', 'subsection_display_order'],
                'indexes': [models.Index(fields=['grade_id'], name='assessment__grade_i_88b7a0_idx'), models.Index(fields=['assessment_id'], name='assessment__assessm_7f3015_idx'), models.Index(fields=['section_id'], name='assessment__section_46b853_idx'), models.Index(fields=['subsection_id'], name='assessment__subsect_d331a7_idx')],
            },
        ),
    ]
