# Generated by Django 5.2.11 on 2026-08-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentstructure',
            name='section_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentstructure',
            name='section_display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentstructure',
            name='section_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
