# Generated by Django 5.2.11 on 2026-08-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_code', models.CharField(max_length=30, unique=True)),
                ('subsection_id', models.BigIntegerField()),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRUE_FALSE', 'True / False'), ('TEXT', 'Text')], max_length=30)),
                ('question_text', models.TextField()),
                ('question_image', models.FileField(blank=True, null=True, upload_to='questions/')),
                ('options_json', models.JSONField(blank=True, null=True)),
                ('option_image', models.FileField(blank=True, null=True, upload_to='question_options/')),
                ('correct_answer_json', models.JSONField(blank=True, null=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('negative_marks', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['subsection_id', 'display_order'],
                'indexes': [models.Index(fields=['subsection_id'], name='questions_subsect_01d589_idx'), models.Index(fields=['status'], name='questions_status_7bb3dd_idx')],
                'constraints': [models.UniqueConstraint(fields=('subsection_id', 'display_order'), name='unique_question_order_per_subsection')],
            },
        ),
    ]
