# Generated by Django 5.2.11 on 2026-08-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_image',
            field=models.FileField(blank=True, null=True, upload_to='questions/question_options/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.FileField(blank=True, null=True, upload_to='questions/images/'),
        ),
    ]
